#1
CREATE TABLE CUSTOMER
(
CID INT ,
CNAME VARCHAR(25) NOT NULL,
LOC VARCHAR(25),
SEX VARCHAR(10),
DOB DATE
);

CREATE TABLE BANK_BRN
(
BCODE INT, #PRIMARY KEY,
BLOC VARCHAR(25),
BSATE VARCHAR(25)
);

CREATE TABLE DEPOSIT
(
DACNO INT, #PRIMARY KEY,
DTYPE VARCHAR(25),
DDATE DATE,
DAMT INT
);

CREATE TABLE LOAN
(
LACNO INT,# PRIMARY KEY,
LTYPE VARCHAR(25),
LDATE DATE,
LAMT INT
);

CREATE TABLE ACCOUNTS_IN
(
BCODE INT,
CID INT
#CONSTRAINT FK_BCODE FOREIGN KEY(BCODE) REFERENCES BANK_BRN(BCODE),
#CONSTRAINT FK_CID FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)
);

CREATE TABLE DEPOSITOR
(
CID INT,
DACNO INT
#CONSTRAINT FK_CID FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
#CONSTRAINT FK_DACNO FOREIGN KEY(DACNO) REFERENCES DEPOSIT(DACNO)
);

CREATE TABLE BORROWER
(
CID INT,
LACNO INT
#CONSTRAINT FK_CID FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
#CONSTRAINT FK_LACNO FOREIGN KEY(LACNO) REFERENCES LOAN(LACNO)
);

#2
ALTER TABLE CUSTOMER ADD PRIMARY KEY (CID);
ALTER TABLE BANK_BRN ADD PRIMARY KEY (BCODE);
ALTER TABLE DEPOSIT ADD PRIMARY KEY (DACNO);
ALTER TABLE LOAN ADD PRIMARY KEY (LACNO);

ALTER TABLE ACCOUNTS_IN ADD FOREIGN KEY (BCODE) REFERENCES BANK_BRN(BCODE);
ALTER TABLE ACCOUNTS_IN ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE DEPOSITOR ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE DEPOSITOR ADD FOREIGN KEY (DACNO) REFERENCES DEPOSIT(DACNO);
ALTER TABLE BORROWER ADD FOREIGN KEY (CID) REFERENCES CUSTOMER(CID);
ALTER TABLE BORROWER ADD FOREIGN KEY (LACNO) REFERENCES LOAN(LACNO);

#4
USE BANK;
SHOW TABLES;

#5

DESCRIBE CUSTOMER;
DESCRIBE BANK_BRN;
DESCRIBE DEPOSIT;
DESCRIBE LOAN;
DESCRIBE ACCOUNTS_IN;
DESCRIBE DEPOSITOR;
DESCRIBE BORROWER;

#6

DROP TABLE CUSTOMER;
DROP TABLE BANK_BRN;
DROP TABLE DEPOSIT;
DROP TABLE LOAN;
DROP TABLE ACCOUNTS_IN;
DROP TABLE DEPOSITOR;
DROP TABLE BORROWER;